#!/usr/bin/env bash

CONTAINER_ENGING="docker"
DOCKERHUB_USERNAME="REPLACEME"
DOCKERHUB_REPONAME="springboot-container"

${CONTAINER_ENGING} build -f ./Dockerfile -t ${DOCKERHUB_REPONAME} .
${CONTAINER_ENGING} image tag ${DOCKERHUB_REPONAME} ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPONAME}
${CONTAINER_ENGING} image push ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPONAME}

${CONTAINER_ENGING} build -f ./Dockerfile.alpine -t ${DOCKERHUB_REPONAME}:alpine .
${CONTAINER_ENGING} image tag ${DOCKERHUB_REPONAME}:alpine ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPONAME}:alpine
${CONTAINER_ENGING} image push ${DOCKERHUB_USERNAME}/${DOCKERHUB_REPONAME}:alpine
