---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot
  name: springboot
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: guessi/springboot-container # replace with actual image repo
        name: springboot
        ports:
        - containerPort: 8080
          protocol: TCP
